//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.ProjetoTreinamentoG120.DataApplicator.Logic.Northwind
{

    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using SGI.Common.DataApplicator;
    using Modelo.ProjetoTreinamentoG120.ModelData.Logic.Northwind.Model;
    using System.Linq;

    /// <summary>
    /// EmployeesDataApplicator class DataApplicator
    /// </summary>
    public class EmployeesDataApplicator : WinDataApplicatorEF<NorthwindEntities, Employees>
    {

        public EmployeesDataApplicator(NorthwindEntities contexto)
            : base(contexto)
        {

        }

        public IQueryable<Employees> ObterTodos()
        {
            try
            {
                return this.Contexto.Employees;
            }
            catch
            {
                throw;
            }
        }

        public Employees ObterPorId(int id)
        {
            return this.Contexto.Employees.Find(id);
        }

        public IQueryable<Employees> BuscarPorNome(string nome)
        {
            try
            {

                return this.Contexto.Employees.Where(est => est.FirstName.Contains(nome));
            }
            catch
            {
                throw;
            }
        }
    }

}