//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.ProjetoTreinamentoG120.ModelData.Logic.Northwind.MetaData
{
    
    using System; 
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    /// <summary>
    /// Employees class MetaData
    /// </summary>
    public partial class EmployeesMetaData
    {
        [DisplayName("Código do empregado")]
        [Required(ErrorMessage = "ID do funcionário é necessário")]
        public int EmployeeID { get; set; }

        [DisplayName("Sobrenome")]
        [Required(ErrorMessage = "Sobrenome é necessario")]
        [MaxLength(20, ErrorMessage = "Sobrenome não pode ter mais que 20 caracteres")]
        public string LastName { get; set; }

        [DisplayName("Nome")]
        [Required(ErrorMessage = "O nome é necessário")]
        [MaxLength(10, ErrorMessage = "O nome não pode ter mais de 10 caracteres")]
        public string FirstName { get; set; }

        [DisplayName("Titulo")]
        [MaxLength(30, ErrorMessage = "O título não pode ter mais de 30 caracteres")]
        public string Title { get; set; }

        [DisplayName("Titulo de cortesia")]
        [MaxLength(25, ErrorMessage = "O título de cortesia não pode ter mais de 25 caracteres")]
        public string TitleOfCourtesy { get; set; }

        [DisplayName("Data de nascimento")]
        public Nullable<System.DateTime> BirthDate { get; set; }

        [DisplayName("Data de contratação")]
        public Nullable<System.DateTime> HireDate { get; set; }

        [DisplayName("Endereço")]
        [MaxLength(60, ErrorMessage = "Endereço não pode ter mais que 60 caracateres")]
        public string Address { get; set; }

        [DisplayName("Cidade")]
        [MaxLength(15, ErrorMessage = "A cidade não pode ter mais de 15 caracteres")]
        public string City { get; set; }

        [DisplayName("Região")]
        [MaxLength(15, ErrorMessage = "A região não pode ter mais de 15 caracteres")]
        public string Region { get; set; }

        [DisplayName("Codigo Postal")]
        [MaxLength(10, ErrorMessage = "O código postal não pode ter mais de 10 caracteres")]
        public string PostalCode { get; set; }

        [DisplayName("País")]
        [MaxLength(15, ErrorMessage = "O país não pode ter mais de 15 caracteres")]
        public string Country { get; set; }

        [DisplayName("Telefone Residencial")]
        [MaxLength(24, ErrorMessage = "O Telefone residencial não pode ter mais que 24 caracteres")]
        public string HomePhone { get; set; }

        [DisplayName("Extensão")]
        [MaxLength(4, ErrorMessage = "Extensão não pode conter mais que 4 caracteres")]
        public string Extension { get; set; }

        [DisplayName("Foto")]
        public byte[] Photo { get; set; }

        [DisplayName("Notas")]
        public string Notes { get; set; }

        [DisplayName("Reportar para")]
        public Nullable<int> ReportsTo { get; set; }

        [DisplayName("Caminho da foto")]
        [MaxLength(255, ErrorMessage = "O caminho da foto não pode ter mais de 255 caracteres")]
        public string PhotoPath { get; set; }

    }
}

